---
- name: Uninstall Apache
  hosts: ec2
  gather_facts: no
  become: yes

  tasks:

  - name: set up index.html
    file:
      path: /var/www/html/index.html
      state: absent
    notify:
      - restart_apache

  - name: Stop Apache
    service:
      name: httpd
      state: stopped

  - name: Uninstall Apache
    yum:
      name: httpd
      state: absent

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted
