---
- name: Uninstall Apache
  hosts: ec2
  gather_facts: no
  become: yes

  tasks:

  - name: Remove index.html
    file:
      path: /var/www/html/index.html
      state: absent

  - name: Stop Apache
    service:
      name: httpd
      state: stopped

  - name: Uninstall Apache
    yum:
      name: httpd
      state: absent
