---
- name: Install Apache
  hosts: ec2
  gather_facts: yes
  become: yes

  tasks:

  - name: install Apache
    yum:
      name: httpd
      state: latest

  - name: run Apache
    service:
      name: httpd
      state: started

  - name: set up index.html
    copy:
      content: "Welcome to the Ansible Demo"
      dest: /var/www/html/index.html
    notify:
      - restart_apache

  handlers:
    - name: restart_apache
      service:
        name: httpd
        state: restarted
