---
# tasks file for setup-etherpad


- name: Install yum-utils
  yum:
    name: yum-utils
    state: present

- name: YUM Cleanup for unfinished installations
  shell: yum-complete-transaction --cleanup-only

- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - gzip
    - git-core
    - curl
    - python
    - openssl-devel

- name: Install build tools
  yum:
    name: "@Development tools"
    state: latest

- name: Add the user etherpad
  user:
    name: etherpad
    create_home: yes

- name: Add repository
  shell: curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -
  args:
    warn: no

- name: Install nodejs
  yum:
    name: nodejs
    state: present

- name: Create etherpad-lite directory
  file:
    path: /opt/etherpad-lite
    state: directory
    owner: etherpad
    group: etherpad

- name: Clone etherpad repository
  git:
    repo: http://github.com/ether/etherpad-lite.git
    dest: /opt/etherpad-lite
    force: yes
  become: yes
  become_user: etherpad

- name: Copy Service template
  template:
    src: etherpad.service.j2
    dest: /etc/systemd/system/etherpad.service

- name: run Etherpad
  shell: systemctl start etherpad
